# Generated by Django 4.2.16 on 2024-09-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_difficulty_database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='multiplayer',
            new_name='new_game_plus',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AddField(
            model_name='game',
            name='enemy_health',
            field=models.IntegerField(default=100, help_text='Enemy health percentage'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_health',
            field=models.IntegerField(default=100, help_text='Player health percentage'),
        ),
        migrations.AddField(
            model_name='game',
            name='resources',
            field=models.IntegerField(default=100, help_text='Resources percentage'),
        ),
        migrations.AddField(
            model_name='game',
            name='unlockable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('extremely_easy', 'Extremely Easy'), ('very_easy', 'Very Easy'), ('easy', 'Easy'), ('somewhat_easy', 'Somewhat Easy'), ('normal', 'Normal'), ('somewhat_hard', 'Somewhat Hard'), ('hard', 'Hard'), ('very_hard', 'Very Hard'), ('extremely_hard', 'Extremely Hard')], default='normal', max_length=20),
        ),
    ]
