# Generated by Django 4.2.16 on 2024-09-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_difficulty_database', '0002_rename_multiplayer_game_new_game_plus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='enemy_health',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_health',
        ),
        migrations.RemoveField(
            model_name='game',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='game',
            name='unlockable',
        ),
    ]
