# Generated by Django 4.2.16 on 2024-09-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_difficulty_database', '0003_remove_game_enemy_health_remove_game_player_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='enemy_health',
            field=models.IntegerField(default=100, help_text='Enemy health percentage'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_health',
            field=models.IntegerField(default=100, help_text='Player health percentage'),
        ),
        migrations.AddField(
            model_name='game',
            name='resources',
            field=models.IntegerField(default=100, help_text='Resources percentage'),
        ),
        migrations.AddField(
            model_name='game',
            name='unlockable',
            field=models.BooleanField(default=False),
        ),
    ]
