# Generated by Django 4.2.16 on 2024-09-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_difficulty_database', '0004_game_enemy_health_game_player_health_game_resources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
        migrations.AddField(
            model_name='game',
            name='Custom_Difficulty',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='enemy_health',
            field=models.IntegerField(blank=True, help_text='Enemy health percentage', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='new_game_plus',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_health',
            field=models.IntegerField(blank=True, help_text='Player health percentage', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='resources',
            field=models.IntegerField(blank=True, help_text='Resources percentage', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='unlockable',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
