# Generated by Django 4.2.16 on 2024-09-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_difficulty_database', '0005_remove_game_release_date_game_custom_difficulty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='difficulty',
            new_name='default_difficulty',
        ),
        migrations.RemoveField(
            model_name='game',
            name='Custom_Difficulty',
        ),
        migrations.RemoveField(
            model_name='game',
            name='enemy_health',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_health',
        ),
        migrations.RemoveField(
            model_name='game',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='game',
            name='unlockable',
        ),
        migrations.AddField(
            model_name='game',
            name='custom_difficulty_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='difficulty_settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='new_game_plus',
            field=models.BooleanField(default=False),
        ),
    ]
