# Generated by Django 4.2.16 on 2024-09-24 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_difficulty_database', '0010_remove_game_custom_difficulty_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficultysettings',
            name='unlockable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
        migrations.AlterField(
            model_name='difficultysettings',
            name='enemy_health',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='difficultysettings',
            name='player_health',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
