# Generated by Django 4.2.16 on 2024-09-27 13:57

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_difficulty_database', '0011_difficultysettings_unlockable_game_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('preferred_difficulty', models.CharField(choices=[('extremely_easy', 'Extremely Easy'), ('very_easy', 'Very Easy'), ('easy', 'Easy'), ('somewhat_easy', 'Somewhat Easy'), ('normal', 'Normal'), ('somewhat_hard', 'Somewhat Hard'), ('hard', 'Hard'), ('very_hard', 'Very Hard'), ('extremely_hard', 'Extremely Hard')], default='normal', max_length=20)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('favorite_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_difficulty_database.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGamePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_difficulty', models.CharField(choices=[('extremely_easy', 'Extremely Easy'), ('very_easy', 'Very Easy'), ('easy', 'Easy'), ('somewhat_easy', 'Somewhat Easy'), ('normal', 'Normal'), ('somewhat_hard', 'Somewhat Hard'), ('hard', 'Hard'), ('very_hard', 'Very Hard'), ('extremely_hard', 'Extremely Hard')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_difficulty_database.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
