# Generated by Django 4.2.16 on 2024-10-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_difficulty_database', '0012_game_added_by_alter_game_image_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='default_difficulty',
        ),
        migrations.AddField(
            model_name='game',
            name='recommended_difficulty',
            field=models.CharField(choices=[('extremely_easy', 'Extremely Easy'), ('very_easy', 'Very Easy'), ('easy', 'Easy'), ('somewhat_easy', 'Somewhat Easy'), ('normal', 'Normal'), ('somewhat_hard', 'Somewhat Hard'), ('hard', 'Hard'), ('very_hard', 'Very Hard'), ('extremely_hard', 'Extremely Hard')], default='normal', max_length=50),
        ),
    ]
